version: '3.3'
services:

  app:
    image: "roboncode/shorturls"
    tty: false
    restart: always
    ports:
      - 1323
    environment:
      - MONGO_DB=mongodb://mongo_urlshortener:27017
    depends_on:
      - db

  db:
    image: mongo
    container_name: "mongo_urlshortener"
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

